### ISSUE TITLE
Implement guitar audio into readable code.

### ISSUE THREAD

**Issue by andy840119** [klaviotarka/osu-gita#1]
If you are trying to use a microphone to do that, you can try this package:
https://github.com/karaoke-dev/osu-framework-microphone
.
This project is for converting vocal voice into the pitch.
I'm not sure it can work in this project(I don't have a guitar to test it.)

**Comment by klaviotarka** [comment]
I thought about doing it that way but there's 2 problems which will probably introduce errors in the future.

First there's a specific string in a guitar the Low E which is barely detectable by the microphone, and the players will need  to play close to the microphone all the time.
Secondly if there's background noise the guitar noise gets all distorted when it goes inside the microphone so yeah.

I believe linking the guitar with an adapter would be the way choice here.
