### ISSUE TITLE
Will this still be developed in the future?

### ISSUE THREAD

**Issue by Hexality** [klaviotarka/osu-gita#2]
Wanted to know if this will be developed in the future, cause the readme seems promissing.

**Comment by klaviotarka** [comment]
Yes it will,

I am sorry for not updating it, but I've been really busy with my bachelor thesis and work. I will start coding it the moment I am done with my bachelor thesis :)

**Comment by Hexality** [comment]
oh, nice to hear that it is still a thing.
Also, good lucky with your bachelor thesis o7

**Comment by klaviotarka** [comment]
Thanks mate

Will get back to it as soon as I can :)
